#!/bin/bash

# ========== CONFIG ==========
LOG_DIR="./logs"
TIMESTAMP=$(date '+%Y-%m-%d_%H-%M-%S')
LOG_FILE="$LOG_DIR/system_report_$TIMESTAMP.txt"
ALERTS=()

EMAIL_TO="your_email@example.com"  # Replace with your email

# ========== SETUP ==========
mkdir -p "$LOG_DIR"
touch "$LOG_FILE"

log_section() {
    echo -e "\n🟩 $1\n-----------------------------" >> "$LOG_FILE"
}

log_and_alert() {
    local message=$1
    echo "$message" >> "$LOG_FILE"
    ALERTS+=("$message")
}

# ========== REPORT ==========
echo "🔧 System Health Report - $TIMESTAMP" > "$LOG_FILE"
echo "Generated by Khoa Diep's IT Support Toolkit" >> "$LOG_FILE"

log_section "Disk Usage"
df -h >> "$LOG_FILE"
DISK=$(df / | awk 'NR==2 {print $5}' | sed 's/%//')
if [ "$DISK" -gt 85 ]; then
    log_and_alert "⚠️  Warning: Disk usage is above 85% (currently ${DISK}%)"
fi

log_section "Memory Usage (vm_stat)"
MEM_FREE=$(vm_stat | awk '/free/ {print $3}' | sed 's/\.//')
if [ "$MEM_FREE" -lt 50000 ]; then
    log_and_alert "⚠️  Warning: Low free memory detected (less than 50,000 pages)"
fi
vm_stat | grep "Pages" >> "$LOG_FILE"

log_section "CPU Load & Uptime"
uptime >> "$LOG_FILE"

log_section "Top 5 CPU-Consuming Processes"
ps aux | sort -nrk 3 | head -n 6 >> "$LOG_FILE"

log_section "Startup Items"
ls ~/Library/LaunchAgents >> "$LOG_FILE" 2>/dev/null

log_section "macOS Version Info"
system_profiler SPSoftwareDataType | grep "System Version" >> "$LOG_FILE"

echo -e "\n✅ Report saved to: $LOG_FILE"

# ========== EMAIL OPTION ==========
if command -v mail &> /dev/null; then
    mail -s "🖥️ System Report: $TIMESTAMP" -a "$LOG_FILE" "$EMAIL_TO" < /dev/null
    echo "📧 Report emailed to $EMAIL_TO"
else
    echo "📧 'mail' command not available – skipping email notification."
fi
